export interface ICamera { 
    Type?:string,  
    GuidCamera: string,
    GuidUnit: string,
    ArchiverGuid: string,
    Archiver: string,
    SiteName: string,
    LogicalId: number,
    NameCamera: string,
    NameUnit: string,
    Manufacturer: string,
    Model: string,
    DescriptionUnit: string,
    DescriptionCamera: string,
    AudioRecording: boolean,
    AutomaticCleanup: boolean,
    IsActive: boolean,
    RedundantArchiving: boolean,
    RetentionPeriod: number,
    ScheduleRecordingMode: string,
    PingOk: boolean,
    LastPingOk: Date,
    LastUpdate: Date,
    IPAddress: string,
    MacAddress: string,
    IsPtz: boolean,
    CameraRunningState: string,
    UnitRunningState: string,
    CameraSignalState: string,
    CameraRecordingState: string,
    FirmwareVersion: string,
    ParentsTreeStructureGuid:string[],
    TreeStructures: string[],
    UnitHardwareVersion: string,
    UnitIsOnline: boolean,
    CameraIsOnline: boolean,
    UnitIsRunning: boolean,
    IsGeneralStateOk: boolean,
    Latitude: number,
    Longitude: number,
    CreateOrReplaceRequestId: number,
    VideoUnitCreatedOn: Date,
    CameraCreatedOn: Date,
    ServiceName?:string,
    SecurityCenterId?:string
 }