import { ITreeStructure } from "./ITreeStructure";
import { IVideoStream } from "./IVideoStream";

export interface ICameraRequestAdd {
   asChanged?: any; 
   Type?:string,  
    Id: number,
    RequestId: number,
    ArchiverGuid: string,
    CameraGuid: string,
    ArchiverName: string,
    IPAddress: string,
    MacAddress: string,
    LastUpdate: Date,
    LogicalId: number,
    NameCamera: string,
    NameUnit: string,
    Manufacturer: string,
    Model: string,
    DescriptionCamera: string,
    RetentionPeriod: number,
    DescriptionUnit: string,
    RequestCameraState: string,
    RequestCameraStateCode: string,
    SiteName: string,
    IsAskingForPing: boolean,
    IsPingOk: boolean,
    IsIpLocatorOk: boolean,
    IsPtz: boolean,
    Building: string,
    Local: string,
    Bay: string,
    Position: string,
    Brewing: string,
    MasaiCaseNumber: string,
    IsPassword: boolean,
    Password: string,
    Login: string,
    Switch: string,
    Port: string,
    Unity: string,
    ConfigurationItemNumber: string,
    Comment: string,
    CreateInSCResult: string,
    VideoStreams: IVideoStream[],
    TreeStructures: ITreeStructure[]|string[],
 }