export interface IVideoStream { 
    Type?:string,  
    Id: number,
    Name: string,
    SiteName: string,
    LastUpdate: Date,
    ImageQuality: number,
    MulticastAdress: string,
    RecordingFrameInterval: string,
    BitRate: number,
    FrameRate: number,
    ResolutionX: number,
    ResolutionY: number,
    IsImageCropped: boolean,
    KeyFrameInterval: number,
    PreferredConnectionType: string,
    MulticastPort: number,
    Index: number,
    Usages: string[],
 }