import { ILicence } from "./Interfaces/ILicence"
import { ILicencePool } from "./Interfaces/ILicencePool"
import { IRequest } from "./Interfaces/IRequest"
import { ICameraRequestAdd } from "./Interfaces/IRequestCameraAdd"
import { IUserGroup } from "./Interfaces/IUserGroup"
import { IVideoStream } from "./Interfaces/IVideoStream"

interface IDefaultValues{
    request:IRequest,
    requestCameraAdd:ICameraRequestAdd,
    userGroup:IUserGroup,
    videoStream:IVideoStream,
    licencePool:ILicencePool,
    licence:ILicence
}

export const DEFAULT_VALUES:IDefaultValues = {
    request: {
        Id: 0,
        SiteName: null,
        Title:  null,
        MasaiCaseNumber: null,
        NumberOfCamerasRequested: null,
        Comment: "",
        LastUpdate: new Date,
        RequestType: null,
        ServiceName: null,
        RequestState: null,
        NumberOfCameras: 0,
        NumberOfRequestCameraByStates: [],
        RequestTypeCode: null,
        LicenseId: null,
        LicensePoolId: null,
        LicenseName: null,
        ServiceCode: null,
        RequestStateCode: null,
        Cameras:[]
    },
    requestCameraAdd:{
        Id: 0,
        RequestId: 0,
        ArchiverGuid: "00000000-0000-0000-0000-000000000000",
        CameraGuid: "00000000-0000-0000-0000-000000000000",
        ArchiverName: null,
        IPAddress: "0.0.0.0",
        MacAddress: "00:00:00:00:00",
        LastUpdate: new Date,
        LogicalId: null,
        NameCamera: null,
        NameUnit: null,
        Manufacturer: null,
        Model: null,
        DescriptionCamera: "",
        RetentionPeriod: 0,
        DescriptionUnit: null,
        RequestCameraState: "ADD",
        RequestCameraStateCode: "1ADD",
        SiteName: null,
        IsAskingForPing: false,
        IsPingOk: false,
        IsIpLocatorOk: false,
        IsPtz: false,
        Building: "",
        Local: "",
        Bay: "",
        Position: "",
        Brewing: "non",
        MasaiCaseNumber: null,
        IsDefaultPassword: true,
        Password: "",
        Login: "",
        Switch: "",
        Port: "",
        Unity: "",
        ConfigurationItemNumber: "",
        Comment: "",
        CreateInSCResult: "",
        VideoStreams: [],
        TreeStructures: [],
        DateToDelete: new Date,
        CameraToDeleteGuid: null,
        VideoUnitToDeleteGuid: null
    },
    userGroup: {
        Name: "",
        RoleCode: "",
        SiteCodes: [],
        isNew:true,
    },
    videoStream:{
        Id: 0,
        Name: "",
        SiteName: "",
        LastUpdate: null,
        ImageQuality: null,
        MulticastAdress: null,
        RecordingFrameInterval: null,
        BitRate: null,
        FrameRate: null,
        ResolutionX: null,
        ResolutionY: null,
        IsImageCropped: false,
        KeyFrameInterval: null,
        PreferredConnectionType: null,
        MulticastPort: null,
        Index: 0,
        Usages: []
    },
    licencePool:{
        Id: 0,
        SiteName: "",
        ServiceCode: "",
        Name: "",
        ExpectedEndDate: undefined,
        IsProject: false,
        Quantity: 0,
        CameraQuantity: 0,
        CloseDate: undefined,
        IsClose: false,
        CreationDate: undefined,
        Licenses: [],
        Status: []
    },
    licence:{
        Id: 0,
        SiteName: "",
        ServiceCode: "",
        Name: "",
        ChargeCode: "",
        Comment: "",
        Quantity: 0,
        CameraQuantity: 0,
        UpdateDate: undefined,
        Applicant: "",
        ChargeOrderNumber: "",
        InvoiceDate: undefined
    }
}