
export const localelanguage = {
    fr:{
        startsWith: "Commence par",
        contains: "Contient",
        notContains: "Ne contient pas",
        endsWith: "Se termine par",
        equals: "Est égal à",
        notEquals: "N'est pas égal à",
        noFilter: "Aucun filtre",
        filter: "filtre", 
        lt: "Est inférieur à",
        lte: "Est inférieur ou égal à",
        gt: "Est supérieur à",
        gte: "Est supérieur ou égal à",
        dateIs: "Date est",
        dateIsNot: "Date n'est pas",
        dateBefore: "Date avant",
        dateAfter: "Date après",
        clear: "Effacer",
        apply: "Appliquer",
        matchAll: "Correspondre à tous",
        matchAny: "Correspondre à n'importe lequel",
        addRule: "Ajouter une règle",
        removeRule: "Supprimer une règle",
        accept: "Accepter",
        reject: "Rejeter",
        close: "Fermer",
        cancel: "Annuler",
        dayNames: ['Dimanche', 'Lundi', 'Mardi', 'Mercredi', 'Jeudi', 'Vendredi', 'Samedi'],
        dayNamesShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
        dayNamesMin: ['D', 'L', 'M', 'M', 'J', 'V', 'S'],
        monthNames: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
        monthNamesShort: ['Janv', 'févr', 'Mars', 'Avr', 'Mai', 'Juin', 'Juil', 'Août', 'Sept', 'Oct', 'Nov', 'Déc'],
        today: 'Aujourd’hui',
        }
}